/* Database schema to keep the structure of entire database. */

CREATE DATABASE clinic_database;

CREATE TABLE patients(
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(150),
  date_of_birth date
);

CREATE TABLE medical_histories(
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  admitted_at DATE,
  patient_id INT REFERENCES patients(id),
  status VARCHAR(100)
);

CREATE INDEX idx_patient_id ON medical_histories(patient_id);

CREATE TABLE treatments (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR(50),
  name VARCHAR(100)
);

CREATE TABLE invoices (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL,
  generated_at DATE,
  payed_at DATE,
  medical_history_id INT REFERENCES medical_histories(id)
);

CREATE INDEX idx_medical_history_id ON invoices(medical_history_id);

CREATE TABLE invoice_items(
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_price DECIMAL,
  quantitiy INT,
  total_price DECIMAL,
  invoice_id INT REFERENCES invoices(id),
  treatment_id INT REFERENCES treatments(id)
);

CREATE INDEX idx_invoice_id ON invoice_items(invoice_id);
CREATE INDEX idx_treatment_id ON invoice_items(treatment_id);

CREATE TABLE treatment_histories(
  medical_histories_id INT REFERENCES medical_histories(id),
  treatments_id INT REFERENCES treatments(id)
);

CREATE INDEX idx_medical_histories_id ON treatment_histories(medical_histories_id);
CREATE INDEX idx_treatments_id ON treatment_histories(treatments_id);
